class BTGUIConstants {
    static BG = "BTGUI_BG"
    static SPIN = "BTGUI_SPIN"
    static AUTO_SPIN = "BTGUI_AUTO_SPIN"
    static AUTO_START = "BTGUI_AUTO_START"
    static AUTO_STOP_SPIN = "BTGUI_AUTO_STOP_SPIN"
    static MENU = "BTGUI_MENU"
    static MENU_BUTTONS = "BTGUI_MENU_BUTTONS"
    static MENU_HOME = "BTGUI_MENU_HOME"
    static MENU_EXIT = "BTGUI_MENU_EXIT"
    static MENU_SOUND_ON = "BTGUI_MENU_SOUND_ON"
    static MENU_SOUND_OFF = "BTGUI_MENU_SOUND_OFF"
    static MENU_OPTIONS_REPLAY = "BTGUI_MENU_OPTIONS_REPLAY"
    static FEATURE_DROP = "BTGUI_FEATURE_DROP"
    static CHANGE_BET = "BTGUI_CHANGE_BET"
    static BUY_BONUS_START = "BTGUI_BUY_BONUS_START"
    static BUY_BONUS_CANCEL = "BTGUI_BUY_BONUS_CANCEL"
    static FREE_SPIN_GAMBLE = "BTGUI_FREE_SPIN_GAMBLE"
    static FREE_SPIN_START = "BTGUI_FREE_SPIN_START"
    static FEATURE_DROP_BUY = "BTGUI_FEATURE_DROP_BUY"
    static WHEEL_GAMBLE = "BTGUI_WHEEL_GAMBLE"
    static WHEEL_COLLECT = "BTGUI_WHEEL_COLLECT"
    static CHANGE_BET_PLUS = "BTGUI_CHANGE_BET_PLUS"
    static CHANGE_BET_MINUS = "BTGUI_CHANGE_BET_MINUS"
    static START_BANER_BTN = "BTGUI_START_BANER_BTN"

    //auto 
    static AUTO_NUM_SPINS_PLUS = "BTGUI_AUTO_NUM_SPINS_PLUS"
    static AUTO_NUM_SPINS_MINUS = "BTGUI_AUTO_NUM_SPINS_MINUS"

    static AUTO_LOSS_PLUS = "BTGUI_AUTO_LOSS_PLUS"
    static AUTO_LOSS_MINUS = "BTGUI_AUTO_LOSS_MINUS"

    static AUTO_WIN_PLUS = "BTGUI_AUTO_WIN_PLUS"
    static AUTO_WIN_MINUS = "BTGUI_AUTO_WIN_MINUS"
}

export default BTGUIConstants;